clear;
clc;

%% inputs
x = randi([0 1], 1, 90); %bernoulli

%% raised-cosine filter
rf = 0.25;
span = 4;
sps = 3;
h1 = rcosdesign(rf,span,sps,'normal');
fvtool(h1,'impulse')
fvtool(h1,'magnitude')
%H = reshape(h1(1:12),3,4); %[0,3,6,9];[1,4,7,10];[2,5,8,11];

%% simulation
y_direct = conv(x,h1(1:12)); % direct
Y_sl = short_length(x,h1,3); % short-length
Y_slt = short_length_tp(x,h1,3);

%%
t = 0:29;

figure;
stem(t, x(:, 1:30), 'filled');
ax1 =gca;
axis([0 30 0 1])
set(ax1,...
'Units','normalized',...
'XTick',0:10:30,...
'YTick',0:1,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Magnitude',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Time Index',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');
%%
figure;
stem(t, y_direct(:, 1:30), 'filled');
ax1 =gca;
axis([0 30 0 2])
set(ax1,...
'Units','normalized',...
'XTick',0:10:30,...
'YTick',0:2,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Magnitude',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Time Index',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');
%%
figure;
stem(t, Y_sl(:, 1:30), 'filled');
ax1 =gca;
axis([0 30 0 2])
set(ax1,...
'Units','normalized',...
'XTick',0:10:30,...
'YTick',0:2,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Magnitude',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Time Index',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');
%%
figure;
stem(t, Y_slt(:, 1:30), 'filled');
ax1 =gca;
axis([0 30 0 2])
set(ax1,...
'Units','normalized',...
'XTick',0:10:30,...
'YTick',0:2,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Magnitude',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Time Index',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');


