%% Q1
clear;
clc;

f1 = 1 : 30;
f2 = 1 : 100;

Lp1 = PropaLoss(f1,3);
Lp2 = PropaLoss(f2,4);
Lp3 = PropaLoss(f2,5);

Ln1 = NEXTLoss(f1,3);
Ln2 = NEXTLoss(f2,4);
Ln3 = NEXTLoss(f2,5);

figure;
hold on;
plot(f1,Lp1,'r-','linewidth',2, 'DisplayName','cat3, propa.');
plot(f2,Lp2,'b-','linewidth',2, 'DisplayName','cat4, propa.');
plot(f2,Lp3,'k-','linewidth',2, 'DisplayName','cat5, propa.');
plot(f1,Ln1,'r--','linewidth',2, 'DisplayName','cat3, NEXT');
plot(f2,Ln2,'b--','linewidth',2, 'DisplayName','cat4, NEXT');
plot(f2,Ln3,'k--','linewidth',2, 'DisplayName','cat5, NEXT');

ax1 =gca;
axis([0 100 0 50])
set(ax1,...
'Units','normalized',...
'XTick',0:10:100,...
'YTick',0:10:50,...
'Ydir','reverse',...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Loss (dB)',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Frequency (MHz)',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

legend('show');
