%% Q2-1
clear;
clc;
T = 1/(12.96*1e6);
t = [-4:0.001:-0.1, -0.1:0.01:0.1, 0.1:0.001:4] * 1e-7;

g = zeros(5,size(t,2));
a = [0,0.25,0.5,0.75,1];
for i = 1 : 5
    g(i,:) = raisedcosine(t,T,a(i),'time');
    max(g(i,:));
end

c = ['k','r','b','g','y'];
figure;
hold on;
for i = 1 : 5
    plot(t,g(i,:),c(i),'linewidth',2, 'DisplayName', ...
        strcat('\alpha = ',num2str(a(i))));
end
ax1 =gca;
axis([-4*1e-7 4*1e-7 -0.4 1.6])
set(ax1,...
'Units','normalized',...
'XTick',(-4:4)*1e-7,...
'YTick',-.4:.4:1.6,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Amplitude',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Time (s)',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

legend('show');

%% Q2-2
clear;
clc;
f = (-2 : 0.001 : 2) * 1e7;
T = 1/(12.96*1e6);
G = zeros(5,size(f,2));
a = [0,0.25,0.5,0.75,1];
for i = 1 : 5
    G(i,:) = raisedcosine(f,T,a(i),'freq');
end
c = ['k','r','b','g','y'];
figure;
hold on;
for i = 1 : 5
    plot(f/1e6,G(i,:)/T,c(i),'linewidth',2, 'DisplayName', ...
        strcat('\alpha = ',num2str(a(i))));
end
ax1 =gca;
axis([-20 20 0 1])
set(ax1,...
'Units','normalized',...
'XTick',(-2:2)*10,...
'YTick',0:.2:1,...
'Position',[.15 .2 .75 .7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',14,...
'FontName','Times',...
'linewidth',1.2,...
'TickLength', [0.02 0.035]);

ylabel('Amplitude (Normalized to T)',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

xlabel('Frequency (MHz)',...
'FontUnits','points',...
'interpreter','latex',...
'FontSize',16,...
'FontName','Times');

legend('show');